### ISSUE TITLE
VSCode variables don't work?

### ISSUE THREAD

**Issue by ahogen** [dharrington/vscode-terminal-file-link#1]
Building a project with CMake + Ninja. When there are compiler errors, the are shown as being relative to the `./build` directory, not the project root directory. 

So I thought I'd give this extension a try, see if it could help speed up my workflow.

My build folder is always `./build`, so I added the following to my settings:

```
  "terminalFileLink.baseDirectories": [
    "${workspaceFolder}/build"
  ]
```

But that didn't seem to work. I had to use an absolute path to that `build` directory to get it to work. Any thoughts?

**EDIT:** Found the problem: https://github.com/microsoft/vscode/issues/2809

So unfortunately this plugin won't help due to VSCode limitations, I guess. 😢

**Comment by dharrington** [comment]
Note that you can set baseDirectories in your workspace-specific settings. I've published a new version which supports ${workspaceFolder} substitution explicitly.

**Comment by ahogen** [comment]
Just had a chance to try out your change. 

If I put the absolute path in the `terminalFileLink.baseDirectories` list, that works. But if I try to use `${workspaceFolder}/build` instead, it doesn't work.

In the "Output" tab (e.g. Ctrl+P -> type "focus on Output") and pick this extension's output, I see

```
Initialized with /c:/my/path/build
```

Is that first slash correct? I would expect `c:/my/path/build` 🤔
