### ISSUE TITLE
Support multi-root workspaces

### ISSUE THREAD

**Issue by mjpieters** [dharrington/vscode-terminal-file-link#3]
Please support workspaces with [more than one root](https://code.visualstudio.com/docs/editor/multi-root-workspaces).

Currently, `${workspaceFolder}` is expanded to just the _first_ workspace root. You could expand it to _all_ workspace roots:

```javascript
        baseDirectories = baseDirectories.reduce((acc, d) => {
            if (vscode.workspace.workspaceFolders && d.includes("${workspaceFolder}")) {
                return acc.concat(
                    vscode.workspace.workspaceFolders.map(
                        (wsf) => d.replace("${workspaceFolder}", wsf.uri.path)
                    )
                );
            }
            return acc.concat([d]);
        }, []);
```

**Comment by dharrington** [comment]
You can just manually configure baseDirectories. Patches accepted though

**Comment by mjpieters** [comment]
> You can just manually configure baseDirectories. Patches accepted though

Well, not really, not and maintain portability because you'd have to put in the full path to each wor. I'll create a PR.
