### ISSUE TITLE
Bug: creates multiple output channels

### ISSUE THREAD

**Issue by mjpieters** [dharrington/vscode-terminal-file-link#4]
The extension creates a new output channel each time the configuration is changed, resulting in a rather cluttered OUTPUT tab picker. That's because the `vscode.workspace.onDidChangeConfiguration()` event handler calls `init()` every time the configuration for the extension has been changed.

This can be fixed trivially; move the `let logOut = vscode.window.createOutputChannel(...)` call *outside* of `init()`, but still inside `activate(context)`:

```javascript
function activate(context) {
    let logOut = vscode.window.createOutputChannel("terminal-file-link");
    const init = () => {
        // ...
    };
    context.subscriptions.push(vscode.workspace.onDidChangeConfiguration((event) => {
        if (event.affectsConfiguration('terminalFileLink')) {
            init();
        }
    }));
    init();
}
```

**Comment by dharrington** [comment]
Can you send a patch?
